import { listingRecommendations } from './recommendation-listings.mjs?v=1';

export function listingBody(p, seller, { image, icon, cropAsset, productPhoto, productRec, money, escape, later }) {
  const rating = `<div class="rating">${seller.rating} <span class="stars">${Array.from({length:5},()=>image('4f8d0.svg')).join('')}</span> ${seller.reviewCount}</div>`;
  const benefitDefinitions = {
    fitting:['Можно примерить','Только в пунктах Авито',[61,550,107,107]],
    installment:['Можно купить в рассрочку','Оформление за 5 минут',[61,722,107,107]],
    returns:['14 дней на возврат','После получения товара',[61,893,107,107]],
  };
  const badges = (p.benefits || []).map(id=>benefitDefinitions[id]);
  const chip = (text,asset) => `<button class="anchor" ${later}>${asset?image(asset):''}${escape(text)}</button>`;
  const recs = listingRecommendations.filter(id=>id!==p.id);
  return `<main class="screen-scroll real-listing" aria-label="Карточка товара" tabindex="-1">
    <div class="gallery horizontal" aria-label="Фотографии товара">${p.gallery.map((file,index)=>`<div class="photo ${index===0?'first':''}"${p.galleryWidth?` style="width:${p.galleryWidth}px;--photo-width:${p.galleryPhotoWidth}px"`:''}>${productPhoto({...p,image:file},'',false)}<span class="photo-count">${index+1} из ${p.gallery.length}</span></div>`).join('')}</div>
    <section class="pad"><p class="product-price"><strong>${money(p.price-p.bonusPerUnit)}</strong></p><p class="price-detail"><s>${money(p.price)}</s> <span>−${money(p.bonusPerUnit)} бонусами</span></p><p class="price-condition">Цена, если спишете бонусы</p><p class="split-copy"><strong>Сплит 0%</strong> на 2 месяца</p><h1 class="product-title">${escape(p.title)}</h1>
    ${p.maxDiscountPrice?`<p class="price-condition">${money(p.maxDiscountPrice)} с максимальной скидкой</p>`:''}${p.availability?`<p class="availability">${escape(p.availability)}</p>`:''}
    <div class="anchors">${p.id!=='sneakers'?chip('История цены'):''}${chip(p.deliveryLabel,'anchor-1-2268.svg')}${p.benefits?.includes('fitting')?chip('Можно примерить','anchor-1-175.svg'):''}${p.postpay?chip('Постоплата'):''}${chip(`От ${money(p.installment)} × 3`,'anchor-1-2315.svg')}${chip(`${seller.rating} · ${seller.reviewCount}`,'anchor-1-2325.svg')}${p.condition?chip(p.condition):''}</div></section>
    <section class="listing-section pad"><p>Самовывоз с оплатой через Авито, от 1 ₽</p><p class="muted">О самовывозе с онлайн-оплатой</p></section>
    <section class="delivery-section"><div class="pad"><h2>Способ получения</h2><p>${escape(p.deliveryIntro || `Доставка в Санкт-Петербург от ${p.deliveryDays}`)}, от <s>${money(p.deliveryOld)}</s> <span class="green">${money(seller.delivery)}</span>${p.walletDelivery?' при оплате кошельком':''}</p></div><div class="delivery-options horizontal">${p.deliveryOptions.map(o=>`<button class="delivery-option" ${later}>${o.label?`<div class="${o.tone}">${escape(o.label)}</div>`:''}<div>${escape(o.carrier)}</div><div class="cost">${o.old?`<s>${money(o.old)}</s> `:''}${money(o.price)}${o.timing?`, ${escape(o.timing)}`:''}</div></button>`).join('')}</div>${p.walletDelivery?'<p class="pad wallet-note">Выгоднее всего — при оплате кошельком</p>':''}</section>
    <section class="listing-section pad"><div class="credit"><h2>${money(p.installment)} × 4 платежа</h2><p>Без переплаты</p><span class="help">${icon('38ff4.svg')}</span><div class="months">${[2,4,6,12].map((n,i)=>`<button class="button ${i===0?'selected':''}" ${later}>${n} мес.</button>`).join('')}</div><div class="payments"><div class="today"><div class="payment-bars"></div><strong>${money(p.installment)}</strong><p>Сегодня</p></div><div><div class="payment-bars rest"><i></i><i></i><i></i></div><strong>Дальше 3 платежа раз в 2 недели</strong><p>Всего за товар — ${money(p.price)}</p></div></div><button class="button primary" ${later}>Купить в рассрочку</button></div></section>
    <section class="listing-section seller-small pad"><h2 class="seller-short"><span>${escape(seller.name)}</span>${seller.online?'<span class="green">в сети</span>':''}</h2>${rating}${seller.response?`<p class="seller-response">${escape(seller.response)}</p>`:''}<div class="contact-buttons">${seller.canCall?`<button class="button" ${later}>Позвонить</button>`:''}<button class="button" ${later}>Написать</button></div></section>
    ${p.city?`<section class="listing-section pad"><h2>Местоположение</h2><p class="location-copy">${escape(p.city)}</p><button class="text-link" ${later}>Узнать подробности</button></section>`:''}
    ${badges.length?`<section class="listing-section listing-benefits pad">${badges.map(([title,description,rect])=>`<div class="badge">${cropAsset('listing/IMG_0241.PNG',rect,'badge-image')}<div><h3>${title}</h3><p>${description}</p></div>${image('14405.svg','arrow')}</div>`).join('')}</section>`:''}
    <section class="listing-section description pad"><h2>Характеристики</h2><div class="properties">${p.properties.map(([key,value])=>`<p><span>${escape(key)}:</span>${escape(value)}</p>`).join('')}</div><h2>Описание</h2><p>${escape(p.description)}</p></section>
    <section class="listing-section banner real-banner"><div class="banner-copy"><h2>Заработайте на новые покупки</h2><p>Для этого продайте старые: собрали их для вас</p><button class="button primary" ${later}>Я в деле</button></div>${cropAsset('listing/IMG_0242.PNG',[624,770,286,424],'banner-art')}</section>
    <section class="listing-section question pad"><h2>Спросите у продавца</h2><div class="question-box"><div class="question-text"><span>Здравствуйте! Где и когда можно посмотреть?</span>${icon('69620.svg')}</div><div class="question-chips">${['Где и когда можно посмотреть?','Сегодня можно посмотреть?','Завтра можно посмотреть?','Отправите Авито Доставкой?'].map(text=>`<button class="button primary" ${later}>${text}</button>`).join('')}</div></div></section>
    ${p.noProductReviews?`<section class="listing-section pad listing-reviews"><h2>Отзывы</h2><p>Об этом и похожих товарах пока нет отзывов, но можно посмотреть, что пишут о продавце</p><button class="button" ${later}>Все отзывы</button></section>`:''}
    <section class="listing-section seller-full pad"><h2>${escape(seller.name)}</h2>${seller.avatar?cropAsset(seller.avatar.image,seller.avatar.crop,'avatar'):''}${rating}<p>${seller.listingCount}</p>${seller.since?`<p class="muted">${escape(seller.since)}</p>`:''}${seller.followers?`<p class="muted">${escape(seller.followers)}</p>`:''}<button class="text-link" ${later}>Подписаться</button>${seller.badges.length?`<div class="badges">${seller.badges.map(text=>`<span>${escape(text)}</span>`).join('')}</div>`:''}${seller.discountCopy?`<p class="seller-discount">${escape(seller.discountCopy)}</p>`:''}</section>
    <section class="listing-section recommendations"><h2 class="pad">Рекомендации</h2><div class="product-recs horizontal">${recs.map(productRec).join('')}</div></section>
    <section class="item-info"><button class="button" ${later}>Пожаловаться на объявление</button>${p.sourceListingId?`<p>Объявление № ${escape(p.sourceListingId)}</p>`:''}</section>
  </main>`;
}
